import type {
  Bird,
  Chick,
  Customer,
  Flock,
  HatchGroup,
  Note,
  Order,
  Pairing,
  Photo,
  Reservation,
  Trait,
  User,
} from "@/lib/types";

export const currentUser: User = {
  id: "user_1",
  name: "HavenHatchr Demo Farm",
  email: "owner@havenhatchr.com",
  plan: "Breeder Pro",
  createdAt: "2026-04-01T12:00:00.000Z",
};

export const customers: Customer[] = [
  {
    id: "customer_1",
    name: "Maple Row Farm",
    email: "maplerow@example.com",
    phone: "555-214-8874",
    location: "Lancaster, PA",
    notes: "Prefers Saturday pickup and blue egg layers.",
    status: "Active",
    createdAt: "2026-03-10T12:00:00.000Z",
  },
  {
    id: "customer_2",
    name: "Clover Hen Co.",
    email: "orders@cloverhen.co",
    phone: "555-782-1313",
    location: "Hudson Valley, NY",
    notes: "Interested in colorful layer assortment.",
    status: "Active",
    createdAt: "2026-03-12T12:00:00.000Z",
  },
  {
    id: "customer_3",
    name: "Elm Hollow Homestead",
    email: "hello@elmhollow.com",
    phone: "555-883-2104",
    location: "Burlington, VT",
    notes: "Repeat buyer, asks for straight run batches.",
    status: "Returning",
    createdAt: "2026-03-18T12:00:00.000Z",
  },
  {
    id: "customer_4",
    name: "Oak & Grain Farm",
    email: "oakgrain@example.com",
    phone: "555-661-9300",
    location: "Finger Lakes, NY",
    notes: "Waiting for next olive egger hatch.",
    status: "Waitlist",
    createdAt: "2026-03-22T12:00:00.000Z",
  },
];

export const flocks: Flock[] = [
  {
    id: "flock_1",
    name: "Blue Meadow",
    breed: "Marans",
    variety: "Blue Copper",
    notes: "Excellent shell color and consistent fertility.",
    active: true,
    createdAt: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "flock_2",
    name: "Golden Fern",
    breed: "Orpington",
    variety: "Buff",
    notes: "Calm temperament and high demand with families.",
    active: true,
    createdAt: "2026-02-08T12:00:00.000Z",
  },
  {
    id: "flock_3",
    name: "Silver Ridge",
    breed: "Ameraucana",
    variety: "Lavender",
    notes: "Tracked for egg color and beard expression.",
    active: true,
    createdAt: "2026-02-12T12:00:00.000Z",
  },
  {
    id: "flock_4",
    name: "Willow Patch",
    breed: "Olive Egger",
    variety: "Mixed Project",
    notes: "Used for future genetics-focused planning.",
    active: true,
    createdAt: "2026-02-19T12:00:00.000Z",
  },
];

export const birds: Bird[] = [
  {
    id: "bird_1",
    name: "Atlas",
    bandNumber: "B-101",
    sex: "Male",
    breed: "Marans",
    variety: "Blue Copper",
    color: "Blue Copper",
    genetics: "Dark egg line, feathered shanks",
    flockId: "flock_1",
    status: "Active",
    notes: "Primary sire for spring hatch planning.",
    photoUrl: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=600&q=80",
    createdAt: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "bird_2",
    name: "Hazel",
    bandNumber: "B-102",
    sex: "Female",
    breed: "Marans",
    variety: "Blue Copper",
    color: "Blue Copper",
    genetics: "Dark egg line, broad chest",
    flockId: "flock_1",
    status: "Active",
    notes: "Good shell consistency.",
    photoUrl: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=600&q=80",
    createdAt: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "bird_3",
    name: "Sunny",
    bandNumber: "B-201",
    sex: "Male",
    breed: "Orpington",
    variety: "Buff",
    color: "Buff",
    genetics: "Large frame, mellow temperament",
    flockId: "flock_2",
    status: "Active",
    notes: "Reliable breeder rooster.",
    photoUrl: "https://images.unsplash.com/photo-1589923188651-268a9765e432?auto=format&fit=crop&w=600&q=80",
    createdAt: "2026-02-08T12:00:00.000Z",
  },
  {
    id: "bird_4",
    name: "Marigold",
    bandNumber: "B-202",
    sex: "Female",
    breed: "Orpington",
    variety: "Buff",
    color: "Buff",
    genetics: "Wide body and calm handling",
    flockId: "flock_2",
    status: "Active",
    notes: "Excellent broody history.",
    photoUrl: "https://images.unsplash.com/photo-1591198936750-16d8e15edb9e?auto=format&fit=crop&w=600&q=80",
    createdAt: "2026-02-08T12:00:00.000Z",
  },
  {
    id: "bird_5",
    name: "Frost",
    bandNumber: "B-301",
    sex: "Male",
    breed: "Ameraucana",
    variety: "Lavender",
    color: "Lavender",
    genetics: "Blue egg line",
    flockId: "flock_3",
    status: "Active",
    notes: "Tracked for blue egg intensity.",
    photoUrl: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=600&q=80",
    createdAt: "2026-02-12T12:00:00.000Z",
  },
  {
    id: "bird_6",
    name: "Pearl",
    bandNumber: "B-302",
    sex: "Female",
    breed: "Ameraucana",
    variety: "Lavender",
    color: "Lavender",
    genetics: "Blue egg line",
    flockId: "flock_3",
    status: "Active",
    notes: "Good beard and muffs.",
    photoUrl: "https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&w=600&q=80",
    createdAt: "2026-02-12T12:00:00.000Z",
  },
];

export const pairings: Pairing[] = [
  {
    id: "pairing_1",
    name: "Blue Meadow Spring Pair",
    sireId: "bird_1",
    damId: "bird_2",
    goals: "Improve shell color and maintain body width.",
    notes: "Candidate for future pairing outcome tool.",
    active: true,
    createdAt: "2026-03-01T12:00:00.000Z",
  },
  {
    id: "pairing_2",
    name: "Golden Fern Family Pair",
    sireId: "bird_3",
    damId: "bird_4",
    goals: "Focus on temperament and consistent buff plumage.",
    notes: "Used for family-friendly listing text examples.",
    active: true,
    createdAt: "2026-03-03T12:00:00.000Z",
  },
];

export const hatchGroups: HatchGroup[] = [
  {
    id: "hatch_1",
    name: "April Blue Meadow Hatch",
    pairingId: "pairing_1",
    setDate: "2026-03-13",
    hatchDate: "2026-04-03",
    eggsSet: 18,
    eggsHatched: 14,
    notes: "Strong hatch rate and healthy early brooder behavior.",
    createdAt: "2026-03-13T12:00:00.000Z",
  },
  {
    id: "hatch_2",
    name: "Silver Ridge Spring Hatch",
    pairingId: "pairing_2",
    setDate: "2026-03-15",
    hatchDate: "2026-04-05",
    eggsSet: 16,
    eggsHatched: 11,
    notes: "Good hatch, but needs color sorting notes.",
    createdAt: "2026-03-15T12:00:00.000Z",
  },
];

export const chicks: Chick[] = [
  {
    id: "chick_1",
    bandNumber: "CH-2041",
    hatchDate: "2026-04-03",
    flockId: "flock_1",
    hatchGroupId: "hatch_1",
    status: "Available",
    sex: "Unknown",
    color: "Blue Copper",
    notes: "Pullet hold candidate",
    photoUrl: "",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
  {
    id: "chick_2",
    bandNumber: "CH-2042",
    hatchDate: "2026-04-03",
    flockId: "flock_2",
    hatchGroupId: "hatch_1",
    status: "Reserved",
    sex: "Unknown",
    color: "Buff",
    notes: "Reserved for Maple Row Farm",
    photoUrl: "",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
  {
    id: "chick_3",
    bandNumber: "CH-2043",
    hatchDate: "2026-04-04",
    flockId: "flock_3",
    hatchGroupId: "hatch_2",
    status: "Holdback",
    sex: "Unknown",
    color: "Lavender",
    notes: "Strong comb and leg color",
    photoUrl: "",
    createdAt: "2026-04-04T12:00:00.000Z",
  },
  {
    id: "chick_4",
    bandNumber: "CH-2044",
    hatchDate: "2026-04-05",
    flockId: "flock_4",
    hatchGroupId: "hatch_2",
    status: "Sold",
    sex: "Unknown",
    color: "Olive mixed",
    notes: "Picked up with spring hatch order",
    photoUrl: "",
    createdAt: "2026-04-05T12:00:00.000Z",
  },
];

export const reservations: Reservation[] = [
  {
    id: "reservation_1",
    customerId: "customer_1",
    requestedSex: "Female",
    requestedBreed: "Marans",
    requestedVariety: "Blue Copper",
    requestedColor: "Dark",
    quantity: 12,
    status: "Matched",
    notes: "Customer asked for dark egg lines if possible.",
    createdAt: "2026-03-24T12:00:00.000Z",
  },
  {
    id: "reservation_2",
    customerId: "customer_2",
    requestedSex: "Straight Run",
    requestedBreed: "Ameraucana",
    requestedVariety: "Lavender",
    requestedColor: "Lavender",
    quantity: 8,
    status: "Waiting",
    notes: "Wants a colorful egg basket starter flock.",
    createdAt: "2026-03-28T12:00:00.000Z",
  },
  {
    id: "reservation_3",
    customerId: "customer_3",
    requestedSex: "Straight Run",
    requestedBreed: "Orpington",
    requestedVariety: "Buff",
    requestedColor: "Buff",
    quantity: 6,
    status: "Completed",
    notes: "Completed from a previous family batch.",
    createdAt: "2026-03-30T12:00:00.000Z",
  },
  {
    id: "reservation_4",
    customerId: "customer_4",
    requestedSex: "Female",
    requestedBreed: "Olive Egger",
    requestedVariety: "Mixed Project",
    requestedColor: "Olive mixed",
    quantity: 4,
    status: "Waiting",
    notes: "Priority request for next olive egger hatch group.",
    createdAt: "2026-04-01T12:00:00.000Z",
  },
];

export const orders: Order[] = [
  {
    id: "order_1",
    customerId: "customer_1",
    chickIds: [
      "chick_2",
      "chick_2001",
      "chick_2002",
      "chick_2003",
      "chick_2004",
      "chick_2005",
      "chick_2006",
      "chick_2007",
      "chick_2008",
      "chick_2009",
      "chick_2010",
      "chick_2011",
    ],
    total: 96,
    status: "Reserved",
    pickupDate: "2026-04-12",
    notes: "Pickup confirmed for Saturday morning.",
    createdAt: "2026-04-01T12:00:00.000Z",
  },
  {
    id: "order_2",
    customerId: "customer_2",
    chickIds: [
      "chick_2012",
      "chick_2013",
      "chick_2014",
      "chick_2015",
      "chick_2016",
      "chick_2017",
      "chick_2018",
      "chick_2019",
    ],
    total: 64,
    status: "Pending",
    pickupDate: "2026-04-14",
    notes: "Waiting for final hatch count.",
    createdAt: "2026-04-02T12:00:00.000Z",
  },
  {
    id: "order_3",
    customerId: "customer_3",
    chickIds: [
      "chick_2020",
      "chick_2021",
      "chick_2022",
      "chick_2023",
      "chick_2024",
      "chick_2025",
      "chick_2026",
      "chick_2027",
      "chick_2028",
      "chick_2029",
      "chick_2030",
      "chick_2031",
      "chick_2032",
      "chick_2033",
      "chick_2034",
      "chick_2035",
    ],
    total: 128,
    status: "Ready",
    pickupDate: "2026-04-16",
    notes: "Repeat order with flexible pickup window.",
    createdAt: "2026-04-04T12:00:00.000Z",
  },
  {
    id: "order_4",
    customerId: "customer_4",
    chickIds: ["chick_2036", "chick_2037", "chick_2038", "chick_2039"],
    total: 40,
    status: "Waitlist",
    pickupDate: "2026-04-19",
    notes: "Move to confirmed if next hatch has enough olive eggers.",
    createdAt: "2026-04-05T12:00:00.000Z",
  },
];

export const traits: Trait[] = [
  {
    id: "trait_1",
    name: "Egg Color",
    category: "Genetics",
    description: "Useful for future pairing analysis and breeding recommendations.",
  },
  {
    id: "trait_2",
    name: "Temperament",
    category: "Behavior",
    description: "Supports customer matching and future listing generation.",
  },
];

export const notes: Note[] = [
  {
    id: "note_1",
    entityType: "flock",
    entityId: "flock_1",
    content: "Best shell color depth seen in this year’s spring pen.",
    createdAt: "2026-04-02T12:00:00.000Z",
  },
  {
    id: "note_2",
    entityType: "customer",
    entityId: "customer_1",
    content: "Customer appreciates proactive pickup reminders.",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
];

export const photos: Photo[] = [
  {
    id: "photo_1",
    entityType: "bird",
    entityId: "bird_1",
    url: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=600&q=80",
    caption: "Atlas, main Blue Meadow sire",
    createdAt: "2026-04-01T12:00:00.000Z",
  },
  {
    id: "photo_2",
    entityType: "chick",
    entityId: "chick_1",
    url: "https://images.unsplash.com/photo-1551717743-49959800b1f6?auto=format&fit=crop&w=600&q=80",
    caption: "April Blue Meadow hatch chick",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
];

export const dashboardStats = [
  {
    label: "Total Customers",
    value: String(customers.length),
    detail: "Shared customer records ready for messaging and waitlists",
  },
  {
    label: "Active Flocks",
    value: String(flocks.filter((flock) => flock.active).length),
    detail: "Breed and variety data organized for breeder planning",
  },
  {
    label: "Chicks Available",
    value: String(chicks.filter((chick) => chick.status === "Available").length),
    detail: "Inventory data is centralized for listings and reservations",
  },
  {
    label: "Reserved Chicks",
    value: String(chicks.filter((chick) => chick.status === "Reserved").length),
    detail: "Order and reservation flows are mapped for automation later",
  },
  {
    label: "Open Reservations",
    value: String(
      reservations.filter((reservation) =>
        ["Waiting", "Matched"].includes(reservation.status),
      ).length,
    ),
    detail: "Breeder requests still waiting on matches or fulfillment",
  },
];

export const platformModules = [
  {
    title: "Genetics Tracking",
    description:
      "Bird, Trait, Pairing, and HatchGroup entities are ready to support lineage and breeding intelligence later.",
  },
  {
    title: "AI Assistant",
    description:
      "The shared type system makes it easier to build farm-aware answers and assistant workflows on top of structured data.",
  },
  {
    title: "Listing Text & Message Drafts",
    description:
      "Customers, chicks, notes, and photos are organized so future AI tools can draft clean outbound content.",
  },
  {
    title: "Analytics & Automation",
    description:
      "Reservations, orders, and hatch results are centralized for dashboards, automations, and waitlist tools.",
  },
];

export const aiWorkbench = [
  {
    lane: "Pairing Outcome Tools",
    summary: "Use pairings, hatch groups, and chick outcomes to guide future breeder decisions.",
    readiness: "Planned",
  },
  {
    lane: "AI Listing Drafts",
    summary: "Generate polished listing copy from chick traits, breeder notes, and photos.",
    readiness: "Stub ready",
  },
  {
    lane: "Customer Reply Drafts",
    summary: "Draft customer reservation updates and pickup reminders from order state.",
    readiness: "Stub ready",
  },
  {
    lane: "Hatch Analytics",
    summary: "Analyze eggs set, hatch rate, and downstream reservation performance.",
    readiness: "Data mapped",
  },
];
