import type {
  Bird,
  Chick,
  Customer,
  Flock,
  HatchGroup,
  Note,
  Order,
  Pairing,
  Photo,
  Reservation,
  Trait,
  User,
} from "@/lib/types";

export const currentUser: User = {
  id: "user_1",
  name: "HavenHatchr Demo Farm",
  email: "owner@havenhatchr.com",
  plan: "Breeder Pro",
  createdAt: "2026-04-01T12:00:00.000Z",
};

export const customers: Customer[] = [
  {
    id: "customer_1",
    name: "Maple Row Farm",
    email: "maplerow@example.com",
    phone: "555-214-8874",
    location: "Lancaster, PA",
    notes: "Prefers Saturday pickup and dark egg layer projects.",
    status: "Active",
    createdAt: "2026-03-10T12:00:00.000Z",
  },
  {
    id: "customer_2",
    name: "Clover Hen Co.",
    email: "orders@cloverhen.co",
    phone: "555-782-1313",
    location: "Hudson Valley, NY",
    notes: "Interested in colorful layer assortment and Ameraucana keepers.",
    status: "Active",
    createdAt: "2026-03-12T12:00:00.000Z",
  },
  {
    id: "customer_3",
    name: "Elm Hollow Homestead",
    email: "hello@elmhollow.com",
    phone: "555-883-2104",
    location: "Burlington, VT",
    notes: "Repeat buyer, asks for straight run batches with calm temperaments.",
    status: "Returning",
    createdAt: "2026-03-18T12:00:00.000Z",
  },
  {
    id: "customer_4",
    name: "Oak & Grain Farm",
    email: "oakgrain@example.com",
    phone: "555-661-9300",
    location: "Finger Lakes, NY",
    notes: "Waiting for next olive egger hatch with mossy shell potential.",
    status: "Waitlist",
    createdAt: "2026-03-22T12:00:00.000Z",
  },
];

export const flocks: Flock[] = [
  {
    id: "flock_1",
    name: "Blue Meadow",
    breed: "Marans",
    variety: "Blue Copper",
    notes: "Excellent shell color and consistent fertility.",
    active: true,
    createdAt: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "flock_2",
    name: "Golden Fern",
    breed: "Orpington",
    variety: "Buff",
    notes: "Calm temperament and high demand with families.",
    active: true,
    createdAt: "2026-02-08T12:00:00.000Z",
  },
  {
    id: "flock_3",
    name: "Silver Ridge",
    breed: "Ameraucana",
    variety: "Lavender",
    notes: "Tracked for egg color, beard expression, and keeper type.",
    active: true,
    createdAt: "2026-02-12T12:00:00.000Z",
  },
  {
    id: "flock_4",
    name: "Willow Patch",
    breed: "Olive Egger",
    variety: "Mossy Project",
    notes: "Used for olive shell depth and bloom-focused crossing decisions.",
    active: true,
    createdAt: "2026-02-19T12:00:00.000Z",
  },
];

export const birds: Bird[] = [
  {
    id: "bird_1",
    name: "Atlas",
    bandNumber: "B-101",
    sex: "Male",
    breed: "Marans",
    variety: "Blue Copper",
    color: "Blue Copper",
    genetics: "Dark egg line, feathered shanks",
    flockId: "flock_1",
    status: "Active",
    notes: "Primary sire for spring hatch planning.",
    photoUrl:
      "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=600&q=80",
    visualTraits: ["Blue Copper", "Feathered Shanks", "Dark Egg Line"],
    carriedTraits: ["Copper Pattern", "Deep Shell Color"],
    genotypeNotes:
      "Strong shell color line with reliable body width and clean feathered shanks.",
    projectTags: ["Dark Egg Project", "Foundation Sire"],
    createdAt: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "bird_2",
    name: "Hazel",
    bandNumber: "B-102",
    sex: "Female",
    breed: "Marans",
    variety: "Blue Copper",
    color: "Blue Copper",
    genetics: "Dark egg line, broad chest",
    flockId: "flock_1",
    status: "Active",
    notes: "Good shell consistency and hatch vigor.",
    photoUrl:
      "https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=600&q=80",
    visualTraits: ["Blue Copper", "Broad Chest", "Dark Shell"],
    carriedTraits: ["Copper Pattern", "Body Width"],
    genotypeNotes:
      "Reliable dam for shell color consistency and balanced body shape.",
    projectTags: ["Dark Egg Project", "Keeper Dam"],
    createdAt: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "bird_3",
    name: "Sunny",
    bandNumber: "B-201",
    sex: "Male",
    breed: "Orpington",
    variety: "Buff",
    color: "Buff",
    genetics: "Large frame, mellow temperament",
    flockId: "flock_2",
    status: "Active",
    notes: "Reliable breeder rooster.",
    photoUrl:
      "https://images.unsplash.com/photo-1589923188651-268a9765e432?auto=format&fit=crop&w=600&q=80",
    visualTraits: ["Buff Plumage", "Large Frame", "Calm Temperament"],
    carriedTraits: ["Soft Feather Texture", "Wide Body"],
    genotypeNotes:
      "Used for family-friendly temperament goals and even buff color.",
    projectTags: ["Temperament Project", "Family Line"],
    createdAt: "2026-02-08T12:00:00.000Z",
  },
  {
    id: "bird_4",
    name: "Marigold",
    bandNumber: "B-202",
    sex: "Female",
    breed: "Orpington",
    variety: "Buff",
    color: "Buff",
    genetics: "Wide body and calm handling",
    flockId: "flock_2",
    status: "Active",
    notes: "Excellent broody history.",
    photoUrl:
      "https://images.unsplash.com/photo-1591198936750-16d8e15edb9e?auto=format&fit=crop&w=600&q=80",
    visualTraits: ["Buff Plumage", "Wide Body", "Broody"],
    carriedTraits: ["Calm Temperament", "Maternal Strength"],
    genotypeNotes:
      "Broody history and consistent buff color make her key to the temperament line.",
    projectTags: ["Temperament Project", "Maternal Line"],
    createdAt: "2026-02-08T12:00:00.000Z",
  },
  {
    id: "bird_5",
    name: "Frost",
    bandNumber: "B-301",
    sex: "Male",
    breed: "Ameraucana",
    variety: "Lavender",
    color: "Lavender",
    genetics: "Blue egg line",
    flockId: "flock_3",
    status: "Active",
    notes: "Tracked for blue egg intensity.",
    photoUrl:
      "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=600&q=80",
    visualTraits: ["Lavender", "Muffs", "Blue Egg Line"],
    carriedTraits: ["Beard", "Blue Shell Color"],
    genotypeNotes:
      "Selected for lavender type and stronger blue egg carry-through.",
    projectTags: ["Blue Egg Project", "Lavender Line"],
    createdAt: "2026-02-12T12:00:00.000Z",
  },
  {
    id: "bird_6",
    name: "Pearl",
    bandNumber: "B-302",
    sex: "Female",
    breed: "Ameraucana",
    variety: "Lavender",
    color: "Lavender",
    genetics: "Blue egg line",
    flockId: "flock_3",
    status: "Active",
    notes: "Good beard and muff expression.",
    photoUrl:
      "https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&w=600&q=80",
    visualTraits: ["Lavender", "Full Beard", "Blue Egg Line"],
    carriedTraits: ["Muffs", "Blue Shell Color"],
    genotypeNotes:
      "Useful dam for beard quality and cleaner lavender offspring type.",
    projectTags: ["Blue Egg Project", "Keeper Dam"],
    createdAt: "2026-02-12T12:00:00.000Z",
  },
  {
    id: "bird_7",
    name: "Moss",
    bandNumber: "B-401",
    sex: "Male",
    breed: "Olive Egger",
    variety: "Mossy Project",
    color: "Black Copper Olive",
    genetics: "Olive shell modifier, bloom strength",
    flockId: "flock_4",
    status: "Active",
    notes: "Primary sire for mossy olive egg project.",
    photoUrl:
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=600&q=80",
    visualTraits: ["Pea Comb", "Feathered Shanks", "Mossy Olive Shell Line"],
    carriedTraits: ["Blue Shell Color", "Dark Bloom", "Copper Pattern"],
    genotypeNotes:
      "Cross-selected for layered bloom over a deep olive shell base and correct pea comb.",
    projectTags: ["Olive Egg Project", "Shell Depth Trial"],
    createdAt: "2026-02-19T12:00:00.000Z",
  },
  {
    id: "bird_8",
    name: "Juniper",
    bandNumber: "B-402",
    sex: "Female",
    breed: "Olive Egger",
    variety: "Mossy Project",
    color: "Wheaten Olive",
    genetics: "Olive shell depth, clean beard",
    flockId: "flock_4",
    status: "Active",
    notes: "High priority olive layer for shell depth goals.",
    photoUrl:
      "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=600&q=80",
    visualTraits: ["Beard", "Pea Comb", "Olive Shell Depth"],
    carriedTraits: ["Blue Shell Color", "Dark Bloom", "Muffs"],
    genotypeNotes:
      "Consistent olive shell color with cleaner facial feathering than the previous generation.",
    projectTags: ["Olive Egg Project", "Keeper Dam"],
    createdAt: "2026-02-19T12:00:00.000Z",
  },
];

export const pairings: Pairing[] = [
  {
    id: "pairing_1",
    name: "Blue Meadow Spring Pair",
    sireId: "bird_1",
    damId: "bird_2",
    goals: "Improve shell color and maintain body width.",
    targetTraits: ["Dark Egg Line", "Broad Chest", "Copper Pattern"],
    avoidTraits: ["Light Shell Color", "Narrow Body"],
    projectGoal: "Refine the dark egg Marans keeper line for breeder-quality pullets.",
    notes: "Candidate for future pairing outcome tool.",
    active: true,
    createdAt: "2026-03-01T12:00:00.000Z",
  },
  {
    id: "pairing_2",
    name: "Golden Fern Family Pair",
    sireId: "bird_3",
    damId: "bird_4",
    goals: "Focus on temperament and consistent buff plumage.",
    targetTraits: ["Buff Plumage", "Calm Temperament", "Wide Body"],
    avoidTraits: ["Patchy Color", "Flighty Temperament"],
    projectGoal:
      "Produce family-friendly Buff Orpington chicks with strong pet-home appeal.",
    notes: "Used for family-friendly listing text examples.",
    active: true,
    createdAt: "2026-03-03T12:00:00.000Z",
  },
  {
    id: "pairing_3",
    name: "Silver Ridge Lavender Pair",
    sireId: "bird_5",
    damId: "bird_6",
    goals: "Strengthen blue egg color and clean lavender type.",
    targetTraits: ["Lavender", "Blue Egg Line", "Full Beard"],
    avoidTraits: ["Weak Beard", "Pale Egg Color"],
    projectGoal: "Advance a cleaner lavender Ameraucana project with stronger egg color.",
    notes: "Tracked as a core line for future genetics insights.",
    active: true,
    createdAt: "2026-03-08T12:00:00.000Z",
  },
  {
    id: "pairing_4",
    name: "Willow Patch Olive Depth Pair",
    sireId: "bird_7",
    damId: "bird_8",
    goals: "Increase olive shell saturation while keeping clean pea comb expression.",
    targetTraits: ["Olive Shell Depth", "Dark Bloom", "Pea Comb"],
    avoidTraits: ["Clean Face Loss", "Thin Shell Tint"],
    projectGoal:
      "Push the mossy olive project toward richer shell color and more uniform keeper chicks.",
    notes: "Early keeper candidates are being tagged for shell-depth follow-up.",
    active: true,
    createdAt: "2026-03-12T12:00:00.000Z",
  },
];

export const hatchGroups: HatchGroup[] = [
    {
      id: "hatch_1",
      name: "April Blue Meadow Hatch",
      pairingId: "pairing_1",
      breedDesignation: "Chicken",
      setDate: "2026-03-13",
      lockdownDate: "2026-03-31",
      hatchDate: "2026-04-03",
      eggsSet: 18,
    eggsHatched: 14,
    producedTraitsSummary: "Mostly blue copper chicks with dark shell line potential.",
    notes: "Strong hatch rate and healthy early brooder behavior.",
    createdAt: "2026-03-13T12:00:00.000Z",
  },
    {
      id: "hatch_2",
      name: "Golden Fern Spring Hatch",
      pairingId: "pairing_2",
      breedDesignation: "Chicken",
      setDate: "2026-03-15",
      lockdownDate: "2026-04-02",
      hatchDate: "2026-04-05",
    eggsSet: 16,
    eggsHatched: 11,
    producedTraitsSummary: "Buff chicks with calm handling and wide-body keeper potential.",
    notes: "Good hatch, but needs color sorting notes.",
    createdAt: "2026-03-15T12:00:00.000Z",
  },
    {
      id: "hatch_3",
      name: "Silver Ridge Lavender Hatch",
      pairingId: "pairing_3",
      breedDesignation: "Chicken",
      setDate: "2026-03-20",
      lockdownDate: "2026-04-05",
      hatchDate: "2026-04-08",
    eggsSet: 14,
    eggsHatched: 10,
    producedTraitsSummary:
      "Lavender chicks showing strong muff development and blue egg promise.",
    notes: "Solid hatch with several keeper candidates already flagged.",
    createdAt: "2026-03-20T12:00:00.000Z",
  },
    {
      id: "hatch_4",
      name: "Willow Patch Olive Trial Hatch",
      pairingId: "pairing_4",
      breedDesignation: "Chicken",
      setDate: "2026-03-24",
      lockdownDate: "2026-04-07",
      hatchDate: "2026-04-10",
    eggsSet: 15,
    eggsHatched: 9,
    producedTraitsSummary:
      "Olive egger chicks with dark legs, pea combs, and several bloom-heavy prospects.",
    notes: "Keeper notes are focused on shell-depth predictors and clean facial feathering.",
    createdAt: "2026-03-24T12:00:00.000Z",
  },
];

export const chicks: Chick[] = [
  {
    id: "chick_1",
    bandNumber: "CH-2041",
    hatchDate: "2026-04-03",
    flockId: "flock_1",
    hatchGroupId: "hatch_1",
    status: "Available",
    sex: "Unknown",
    color: "Blue Copper",
    observedTraits: ["Blue Copper", "Pullet Hold Candidate"],
    notes: "Pullet hold candidate.",
    photoUrl: "",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
  {
    id: "chick_2",
    bandNumber: "CH-2042",
    hatchDate: "2026-04-03",
    flockId: "flock_1",
    hatchGroupId: "hatch_1",
    status: "Reserved",
    sex: "Unknown",
    color: "Blue Copper",
    observedTraits: ["Blue Copper", "Dark Legs", "Copper Leakage"],
    notes: "Reserved for Maple Row Farm.",
    photoUrl: "",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
  {
    id: "chick_3",
    bandNumber: "CH-2143",
    hatchDate: "2026-04-05",
    flockId: "flock_2",
    hatchGroupId: "hatch_2",
    status: "Holdback",
    sex: "Unknown",
    color: "Buff",
    observedTraits: ["Buff", "Wide Body", "Calm Brooder"],
    notes: "Strong width and calm brooder behavior.",
    photoUrl: "",
    createdAt: "2026-04-05T12:00:00.000Z",
  },
  {
    id: "chick_4",
    bandNumber: "CH-2144",
    hatchDate: "2026-04-05",
    flockId: "flock_2",
    hatchGroupId: "hatch_2",
    status: "Sold",
    sex: "Unknown",
    color: "Buff",
    observedTraits: ["Buff", "Family Batch"],
    notes: "Placed in a family starter order.",
    photoUrl: "",
    createdAt: "2026-04-05T12:00:00.000Z",
  },
  {
    id: "chick_5",
    bandNumber: "CH-2241",
    hatchDate: "2026-04-08",
    flockId: "flock_3",
    hatchGroupId: "hatch_3",
    status: "Available",
    sex: "Unknown",
    color: "Lavender",
    observedTraits: ["Lavender", "Muffs", "Clean Beard"],
    notes: "Promising muff development and leg color.",
    photoUrl: "",
    createdAt: "2026-04-08T12:00:00.000Z",
  },
  {
    id: "chick_6",
    bandNumber: "CH-2242",
    hatchDate: "2026-04-08",
    flockId: "flock_3",
    hatchGroupId: "hatch_3",
    status: "Reserved",
    sex: "Unknown",
    color: "Lavender",
    observedTraits: ["Lavender", "Blue Egg Project", "Full Beard"],
    notes: "Tentatively matched to Clover Hen Co.",
    photoUrl: "",
    createdAt: "2026-04-08T12:00:00.000Z",
  },
  {
    id: "chick_7",
    bandNumber: "CH-2341",
    hatchDate: "2026-04-10",
    flockId: "flock_4",
    hatchGroupId: "hatch_4",
    status: "Available",
    sex: "Unknown",
    color: "Mossy Olive",
    observedTraits: ["Pea Comb", "Dark Legs", "Olive Project"],
    notes: "Early shell-depth project candidate from Willow Patch.",
    photoUrl: "",
    createdAt: "2026-04-10T12:00:00.000Z",
  },
  {
    id: "chick_8",
    bandNumber: "CH-2342",
    hatchDate: "2026-04-10",
    flockId: "flock_4",
    hatchGroupId: "hatch_4",
    status: "Holdback",
    sex: "Unknown",
    color: "Wheaten Olive",
    observedTraits: ["Beard", "Pea Comb", "Bloom Heavy"],
    notes: "Flagged as a possible keeper for shell depth follow-up.",
    photoUrl: "",
    createdAt: "2026-04-10T12:00:00.000Z",
  },
];

export const reservations: Reservation[] = [
  {
    id: "reservation_1",
    customerId: "customer_1",
    requestedSex: "Female",
    requestedBreed: "Marans",
    requestedVariety: "Blue Copper",
    requestedColor: "Dark",
    quantity: 12,
    status: "Matched",
    notes: "Customer asked for dark egg lines if possible.",
    createdAt: "2026-03-24T12:00:00.000Z",
  },
  {
    id: "reservation_2",
    customerId: "customer_2",
    requestedSex: "Straight Run",
    requestedBreed: "Ameraucana",
    requestedVariety: "Lavender",
    requestedColor: "Lavender",
    quantity: 8,
    status: "Waiting",
    notes: "Wants a colorful egg basket starter flock.",
    createdAt: "2026-03-28T12:00:00.000Z",
  },
  {
    id: "reservation_3",
    customerId: "customer_3",
    requestedSex: "Straight Run",
    requestedBreed: "Orpington",
    requestedVariety: "Buff",
    requestedColor: "Buff",
    quantity: 6,
    status: "Completed",
    notes: "Completed from a previous family batch.",
    createdAt: "2026-03-30T12:00:00.000Z",
  },
  {
    id: "reservation_4",
    customerId: "customer_4",
    requestedSex: "Female",
    requestedBreed: "Olive Egger",
    requestedVariety: "Mossy Project",
    requestedColor: "Olive mixed",
    quantity: 4,
    status: "Waiting",
    notes: "Priority request for next olive egger hatch group.",
    createdAt: "2026-04-01T12:00:00.000Z",
  },
  {
    id: "reservation_5",
    customerId: "customer_2",
    requestedSex: "Female",
    requestedBreed: "Ameraucana",
    requestedVariety: "Lavender",
    requestedColor: "Soft Lavender",
    quantity: 4,
    status: "Matched",
    notes: "Looking for keeper-quality pullets with fuller beard and muff expression.",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
  {
    id: "reservation_6",
    customerId: "customer_3",
    requestedSex: "Straight Run",
    requestedBreed: "Olive Egger",
    requestedVariety: "Mossy Project",
    requestedColor: "Deep olive",
    quantity: 5,
    status: "Waiting",
    notes: "Would prefer chicks from the darker shell project if availability allows.",
    createdAt: "2026-04-06T12:00:00.000Z",
  },
];

export const orders: Order[] = [
  {
    id: "order_1",
    customerId: "customer_1",
    chickIds: [
      "chick_2",
      "chick_2001",
      "chick_2002",
      "chick_2003",
      "chick_2004",
      "chick_2005",
      "chick_2006",
      "chick_2007",
      "chick_2008",
      "chick_2009",
      "chick_2010",
      "chick_2011",
    ],
    total: 96,
    status: "Reserved",
    pickupDate: "2026-04-12",
    notes: "Pickup confirmed for Saturday morning.",
    createdAt: "2026-04-01T12:00:00.000Z",
  },
  {
    id: "order_2",
    customerId: "customer_2",
    chickIds: [
      "chick_2012",
      "chick_2013",
      "chick_2014",
      "chick_2015",
      "chick_2016",
      "chick_2017",
      "chick_2018",
      "chick_2019",
    ],
    total: 64,
    status: "Pending",
    pickupDate: "2026-04-14",
    notes: "Waiting for final hatch count.",
    createdAt: "2026-04-02T12:00:00.000Z",
  },
  {
    id: "order_3",
    customerId: "customer_3",
    chickIds: [
      "chick_2020",
      "chick_2021",
      "chick_2022",
      "chick_2023",
      "chick_2024",
      "chick_2025",
      "chick_2026",
      "chick_2027",
      "chick_2028",
      "chick_2029",
      "chick_2030",
      "chick_2031",
      "chick_2032",
      "chick_2033",
      "chick_2034",
      "chick_2035",
    ],
    total: 128,
    status: "Ready",
    pickupDate: "2026-04-16",
    notes: "Repeat order with flexible pickup window.",
    createdAt: "2026-04-04T12:00:00.000Z",
  },
  {
    id: "order_4",
    customerId: "customer_4",
    chickIds: ["chick_2036", "chick_2037", "chick_2038", "chick_2039"],
    total: 40,
    status: "Waitlist",
    pickupDate: "2026-04-19",
    notes: "Move to confirmed if next hatch has enough olive eggers.",
    createdAt: "2026-04-05T12:00:00.000Z",
  },
];

export const traits: Trait[] = [
  {
    id: "trait_1",
    name: "Dark Egg Line",
    category: "Shell Color",
    description: "Selected in Marans lines to concentrate shell depth and pigment consistency.",
  },
  {
    id: "trait_2",
    name: "Olive Shell Depth",
    category: "Shell Color",
    description: "Useful in olive egger projects where mossy green shell saturation is the main goal.",
  },
  {
    id: "trait_3",
    name: "Blue Shell Color",
    category: "Carrier",
    description: "Tracked as a carried trait to preserve blue and olive egg project outcomes.",
  },
  {
    id: "trait_4",
    name: "Feathered Shanks",
    category: "Visual",
    description: "Maintained in Marans lines to preserve breed character and profile consistency.",
  },
  {
    id: "trait_5",
    name: "Beard",
    category: "Visual",
    description: "Tracked for Ameraucana and olive egger facial feathering quality.",
  },
  {
    id: "trait_6",
    name: "Muffs",
    category: "Visual",
    description: "Useful for evaluating head furnishings and breeder type in blue egg projects.",
  },
  {
    id: "trait_7",
    name: "Pea Comb",
    category: "Conformation",
    description: "Important in olive egger projects to keep the right head type and project identity.",
  },
  {
    id: "trait_8",
    name: "Body Width",
    category: "Conformation",
    description: "Supports selection goals for balanced type and stronger breeder utility.",
  },
  {
    id: "trait_9",
    name: "Calm Temperament",
    category: "Behavior",
    description: "Used in family-focused lines and customer matching decisions.",
  },
  {
    id: "trait_10",
    name: "Broody Tendency",
    category: "Behavior",
    description: "Helpful for evaluating maternal lines and hatch planning choices.",
  },
];

export const notes: Note[] = [
  {
    id: "note_1",
    entityType: "flock",
    entityId: "flock_1",
    content: "Best shell color depth seen in this year's spring pen.",
    createdAt: "2026-04-02T12:00:00.000Z",
  },
  {
    id: "note_2",
    entityType: "customer",
    entityId: "customer_1",
    content: "Customer appreciates proactive pickup reminders.",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
  {
    id: "note_3",
    entityType: "bird",
    entityId: "bird_1",
    content: "Atlas is staying in the primary Marans sire slot through late spring.",
    createdAt: "2026-04-04T12:00:00.000Z",
  },
  {
    id: "note_4",
    entityType: "bird",
    entityId: "bird_1",
    content: "Strong fertility and consistent dark shell daughters in the first hatch group.",
    createdAt: "2026-04-06T12:00:00.000Z",
  },
  {
    id: "note_5",
    entityType: "bird",
    entityId: "bird_2",
    content: "Hazel's chicks are hatching with especially even vigor and body width.",
    createdAt: "2026-04-05T12:00:00.000Z",
  },
  {
    id: "note_6",
    entityType: "bird",
    entityId: "bird_5",
    content: "Frost is being watched closely for egg color carry-through in the lavender line.",
    createdAt: "2026-04-07T12:00:00.000Z",
  },
  {
    id: "note_7",
    entityType: "bird",
    entityId: "bird_8",
    content: "Juniper has become a priority dam for the shell-depth keeper pen.",
    createdAt: "2026-04-07T18:00:00.000Z",
  },
];

export const photos: Photo[] = [
  {
    id: "photo_1",
    entityType: "bird",
    entityId: "bird_1",
    url: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=600&q=80",
    caption: "Atlas, main Blue Meadow sire",
    createdAt: "2026-04-01T12:00:00.000Z",
  },
  {
    id: "photo_2",
    entityType: "bird",
    entityId: "bird_2",
    url: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=600&q=80",
    caption: "Hazel in the Blue Meadow breeder pen",
    createdAt: "2026-04-02T12:00:00.000Z",
  },
  {
    id: "photo_3",
    entityType: "bird",
    entityId: "bird_3",
    url: "https://images.unsplash.com/photo-1589923188651-268a9765e432?auto=format&fit=crop&w=600&q=80",
    caption: "Sunny, the Golden Fern sire",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
  {
    id: "photo_4",
    entityType: "bird",
    entityId: "bird_5",
    url: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=600&q=80",
    caption: "Frost during the Silver Ridge pairing season",
    createdAt: "2026-04-04T12:00:00.000Z",
  },
  {
    id: "photo_5",
    entityType: "bird",
    entityId: "bird_8",
    url: "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=600&q=80",
    caption: "Juniper, key Willow Patch olive egg project hen",
    createdAt: "2026-04-05T12:00:00.000Z",
  },
  {
    id: "photo_6",
    entityType: "chick",
    entityId: "chick_7",
    url: "https://images.unsplash.com/photo-1551717743-49959800b1f6?auto=format&fit=crop&w=600&q=80",
    caption: "Willow Patch olive project chick",
    createdAt: "2026-04-10T12:00:00.000Z",
  },
];

export const dashboardStats = [
  {
    label: "Total Customers",
    value: String(customers.length),
    detail: "Shared customer records ready for messaging and waitlists",
  },
  {
    label: "Active Flocks",
    value: String(flocks.filter((flock) => flock.active).length),
    detail: "Breed and variety data organized for breeder planning",
  },
  {
    label: "Chicks Available",
    value: String(chicks.filter((chick) => chick.status === "Available").length),
    detail: "Inventory data is centralized for listings and reservations",
  },
  {
    label: "Reserved Chicks",
    value: String(chicks.filter((chick) => chick.status === "Reserved").length),
    detail: "Order and reservation flows are mapped for automation later",
  },
  {
    label: "Open Reservations",
    value: String(
      reservations.filter((reservation) =>
        ["Waiting", "Matched"].includes(reservation.status),
      ).length,
    ),
    detail: "Breeder requests still waiting on matches or fulfillment",
  },
];

export const platformModules = [
  {
    title: "Genetics Tracking",
    description:
      "Bird, Trait, Pairing, and HatchGroup entities are structured for lineage review, trait planning, and future genetics intelligence.",
  },
  {
    title: "AI Assistant",
    description:
      "The shared type system makes it easier to build farm-aware answers and assistant workflows on top of structured breeder data.",
  },
  {
    title: "Listing Text & Message Drafts",
    description:
      "Customers, chicks, notes, photos, and genetics context are organized so future AI tools can draft clean outbound content.",
  },
  {
    title: "Analytics & Automation",
    description:
      "Reservations, pairings, hatch results, and trait outcomes are centralized for dashboards and breeder automations.",
  },
];

export const aiWorkbench = [
  {
    lane: "Pairing Outcome Tools",
    summary: "Use pairings, hatch groups, and chick outcomes to guide future breeder decisions.",
    readiness: "Planned",
  },
  {
    lane: "AI Listing Drafts",
    summary: "Generate polished listing copy from chick traits, breeder notes, photos, and project tags.",
    readiness: "Stub ready",
  },
  {
    lane: "Customer Reply Drafts",
    summary: "Draft customer reservation updates and pickup reminders from order state.",
    readiness: "Stub ready",
  },
  {
    lane: "Hatch Analytics",
    summary: "Analyze eggs set, hatch rate, genetic goals, and downstream reservation performance.",
    readiness: "Data mapped",
  },
];
